### PR TITLE
CD-40 footer mandate and copyright layout

### PR DESCRIPTION
**Pull request by left23**
Please see visuals on [issue](https://humanitarian.atlassian.net/browse/CD-40)

**Soft-footer**: remove h2, replace with paragraph tag

**Mandate and copyright**: refactor layout for mobile and tablet so mandate and copyright blocks spans full width

### CODE REVIEW

**Comment by rupl** [comment]
ok this matches the screenshots in the issue when I view in Chrome/FF. In IE11 I noticed that the copyright falls outside the main layout column in the desktop+ breakpoints:

bs-ie11-1239x887

**Review by rupl — CHANGES_REQUESTED** [review]
requesting changes based on screenshot I just uploaded.

**Comment by left23** [comment]
@rupl Good catch, thank you. I've fixed it. In this case, it was the margin: 0 auto being inherited.

However, I've since changed the layout one more time based on designer feedback, to have how it appear as it does on mobile for tablet as well (the ocha logo stacked above its text) and I've got another IE11 flexbox layout issue that looks similar.
I'm adding a screenshot. I need to figure out how to fix it still.

ie-11

**Comment by left23** [comment]
@rupl This is ready for final review. I tested in IE11 to resolve the layout flaw in screenshot above.

**Review by rupl — APPROVED** [review]

**Comment by rupl** [comment]
looks great! The extra spacing between the two paragraphs is much better to my eyes. :shipit: 

Tested in:

* macOS - Safari/Chrome/FF
* Win 8.1 - IE11
* Win 10 - Edge17
* iOS 11.4 - Safari

**Pull request merged**
